version: '2'

services:
  webserver:
    build:
      context: .
      dockerfile: php-apache.Dockerfile
    ports:
      - "8000:80"
    environment:
      - MOODLE_DOCKER_DBNAME= moodle
      - MOODLE_DOCKER_DBUSER= moodle
      - MOODLE_DOCKER_DBUPASS= m00dl3m00dl3
      - MOODLE_DOCKER_DBCOLLATION= utf8mb4_bin
      - MOODLE_DOCKER_DBTYPE= mysqli
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5
    command: >
                --character-set-server=utf8mb4
                --collation-server=utf8mb4_bin
                --innodb_file_format=barracuda
                --innodb_file_per_table=On
                --innodb_large_prefix=On
    environment:
      MYSQL_ROOT_PASSWORD: "m00dl3m00dl3"
      MYSQL_USER: "moodle"
      MYSQL_PASSWORD: "m00dl3m00dl3"
      MYSQL_DATABASE: "moodle"

